#http 端口
server:
  port: 32188
# spring boot
spring:
  application:
    name: performance-test
  profiles:
    default: dev
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#duboo cache
dubbo:
  registry:
    file: /tmp/dubbo/cache